@api = http://localhost:5000/sql


### obtener todo
GET {{api}}

### enviando dato
POST {{api}}
Content-Type: application/json

{
    "status":200,
    "type":"DELETE",
    "body":"{el body akjsdhaksjdhkajshdkjsa 2}",
    "fecha":"10-01"
}
